### ISSUE TITLE
Ikke muligt eller meget meget bøvlet at installere

### ISSUE THREAD

**Issue by inuitviking** [os2datascanner/os2webscanner#4]
Hej,
Jeg ville prøve at installere os2datascanner på en server, men indtil videre har jeg kun haft bøvl.
Jeg har skrevet rigtig meget om, og jeg har prøvet at køre alt i python2 såvel som python3 og ingenting virker. Installationsguiden virker ikke, da alt giver fejl, faktisk bogstavelig talt.

Er dette den forkerte repo til datascanner?

**Comment by dals83** [comment]
Hej inuitviking,
Det er den rigtige os2datascanner. Men der er i de sidste par måneder sket rigtig meget med produktet, så pt er installationsvejledningen ikke up2date. Beklager. Det skal vi nok få sørget får at få gjort.
I hvilken sammenhæng skal du bruge den? Og hvor er det det går galt så skal jeg forsøge at hjælpe dig?
Mvh,
Danni

**Comment by dals83** [comment]
Dejligt at høre der er andre som bruger eller ihvertfald forsøger at bruge datascanner :)
Jeg sørger for at opdatere installationsvejledningen i denne her uge. 
Dependenciesne i master branch skulle meget gerne være up2date. Jeg har aldrig installeret datascanner på debian. Jeg plejer at installere det på ubuntu 16.04. Men vil antage det virker på debian og så, eftersom ubuntu er bygget på debian.

Men prøv lige og vent med at gøre mere til jeg har opdateret installationvejledningen. Så har vi en opdateret reference ramme at arbejde ud fra.

Og hvis Belcom har lavet nogen tiltag til datascanner må i meget gerne lave et pull request.

**Comment by inuitviking** [comment]
Vi forsørger ihvertfald, hehe :P
Repositories kan nogle gange være en smule anderledes mellem Debian og Ubuntu, men det er sjældent at lægge mærke til; det er ihvertfald min erfaring.

Jeg tester gerne på Debian, når den en ny vejledning er kommet. :smile:

Mig vidende har vi ikke lavet noget vedrørende datascanner, men kun arbejdet med webscanner, så der er nok ikke nogle tiltag.

Og tak for svar!

**Comment by dals83** [comment]
Hej igen,

Prøv at kør følgende:
* git clone https://github.com/os2webscanner/os2webscanner.git
* cd os2webscanner
* ./install.sh
Vær sikker på din bruger er en del af sudoers før du kører install.sh

Alle dependencies er up2date i både master og development branchet.
SYSTEM_DEPENDENCIES referer bare til apache2 også er det op til systemet at hente den nyeste version. Så den skulle meget gerne altid hente apache2.4

Start med at sætte det op i udvikler mode.
Se beskrivelse her: https://github.com/os2webscanner/os2webscanner/blob/master/doc/HOWTO_START_DEVEL_SERVER.txt

**Comment by inuitviking** [comment]
Hej
Jeg får denne fejl når jeg kører ./install.sh:
```
Collecting django-postgrespool==0.3.1
  Using cached https://files.pythonhosted.org/packages/42/bf/85ea69cf9807218c0257dd31f1a6b993a3fa41a2372f7eb96ea809b72a35/django-postgrespool-0.3.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-jz5419o5/django-postgrespool/setup.py", line 26, in <module>
        long_description=open('README.rst').read(),
      File "/var/www/os2webscanner/python-env/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1171: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-jz5419o5/django-postgrespool/

ERROR: Unable to install Python package <Django==1.11.9
```

install.sh findes heller ikke i django-os2webscanner mappen (HOW_TO_START_DEVEL_SERVER.txt).
Skal jeg se bort fra det, eller er det hele dækket i install.sh i roden?

**Comment by dals83** [comment]
Forøvrigt kan jeg nævne at vi er igang med at ansibleficere og muligvis også dokcerficere datascanner så det bliver meget nemmere at installere og starte op fremover.

Og så kan jeg lige nævne at os2datascanner og os2webscanner er samme produkt så hvis bellcom har lavet noget udvidelser til os2webscanner vil kode basen meget gerne modtage dem :)

**Comment by inuitviking** [comment]
python3-dev blev installeret.
Der blev ikke spyttet andre fejl ved apt pakkerne.

Det lyder fedt!
Jeg skal nok spørge efter om vi har lavet nogle udvidelser; jeg ved dog ikke om vi har. :)

**Comment by skifter** [comment]
Hej Danni

Alle de ændrings ønsker vi har mødt har vi bedt kommunerne om at sende 
ind til styregruppen. Og herefter tror jeg i har lavet dem. ;-)


/Skifter

**Comment by dals83** [comment]
Hvilken version af debian kører du?

Jeg mistænker du får kørt python 2 i stedet for 3. 
Du kan prøve at ændre line 32 i install.sh til pip3 install $package

**Comment by inuitviking** [comment]
Debian 9.6
Kernel: Linux 4.9.0-7-amd64 (I tilfælde det skulle være relevant)
Fik denne fejl efter at have ændret linje 32 til pip3:
```
Collecting django-postgrespool==0.3.1
  Using cached https://files.pythonhosted.org/packages/42/bf/85ea69cf9807218c0257dd31f1a6b993a3fa41a2372f7eb96ea809b72a35/django-postgrespool-0.3.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-7wa_k6vk/django-postgrespool/setup.py", line 26, in <module>
        long_description=open('README.rst').read(),
      File "/var/www/os2webscanner/python-env/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1171: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-7wa_k6vk/django-postgrespool/
```

**Comment by dals83** [comment]
Det kan være der er noget galt med dit virtualenv.
Kan du ikke prøve at starte forfra i din egen home folder.
* git clone https://github.com/os2webscanner/os2webscanner.git
* cd os2webscanner
* ./install.sh

**Comment by inuitviking** [comment]
Jeg får desværre nøjagtig samme fejl.

**Comment by logandk** [comment]
https://github.com/heroku-python/django-postgrespool/issues/30#issuecomment-393814385

https://xkcd.com/979/

**Comment by dals83** [comment]
Jeg vil henvise alle til https://github.com/os2datascanner/os2datascanner i stedet for.
OS2webscanner fortsætter i stedet som OS2datascanner.
